routes/web.php
<?php


use App\Http\Controllers\Admin\ProductPropertyController;
use App\Http\Controllers\Admin\PropertyController;
use App\Http\Controllers\Admin\PropertyGroupController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\CategoriController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\CommentController;
use App\Http\Controllers\Admin\CommentController as AdminCommentController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use App\Http\Controllers\client\HomeController;
use App\Http\Controllers\Admin\PictureController;
use App\Http\Controllers\Admin\DiscountController;
use App\Http\Controllers\Client\RegisterController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/')->name('client.')->group(function (){
    Route::get('/', [HomeController::class , 'index'])->name('index');

    Route::get('products/{product}',[ClientProductController::class , 'show'])->name('products.show');

   Route::get('/register',[RegisterController::class, 'create'])->name('register');
   Route::post('/register/sendmail',[RegisterController::class, 'sendmail'])->name('register.sendmail');
   Route::get('/register/otp/{user}',[RegisterController::class, 'otp'])->name('register.otp');
   Route::post('/register/verifyOtp/{user}',[RegisterController::class, 'verifyOtp'])->name('register.verifyOtp');
   Route::delete('/register/logout',[RegisterController::class, 'logout'])->name('register.logout');

   Route::post('products/comment/{product}/store',[CommentController::class,'store'])->name('product.comment.store');


});





Route::prefix('/adminpanel')/*->middleware([
    \App\Http\Middleware\CheckPermission::class .':readCat',
    'auth'

]) */    ->group(function (){
Route::get('/', function (){
    return view('admin.home');
});

    Route::resource('categories',CategoriController::class);
/*    Route::get('/categories',[App\Http\Controllers\Admin\CategoriController::class,'index'])->name('categories.index');
    Route::get('/categories/create',[App\Http\Controllers\Admin\CategoriController::class,'create'])->name('categories.create');
    Route::post('/categories/store',[App\Http\Controllers\Admin\CategoriController::class,'store'])->name('categories.store');
    Route::get('/categories/{categori}',[App\Http\Controllers\Admin\CategoriController::class,'edit'])->name('categories.edit');
    Route::patch('/categories/{categori}/edit',[App\Http\Controllers\Admin\CategoriController::class,'update'])->name('categories.update');
    Route::delete('/categories/{categori}',[App\Http\Controllers\Admin\CategoriController::class,'destroy'])->name('categories.destroy');*/
Route::resource('brands', \App\Http\Controllers\admin\BrandController::class);

Route::resource('products',ProductController::class);

Route::resource('products.pictures',PictureController::class);

Route::resource('products.discounts',DiscountController::class);

Route::resource('roles',RoleController::class);

Route::resource('users',UserController::class);

Route::resource('propertyGroup',PropertyGroupController::class);

Route::resource('property',PropertyController::class);

Route::get('products/{product}/propertyProduct/create',[ProductPropertyController::class,'create'])->name('products.propertyProduct.create');
Route::get('products/{product}/propertyProduct',[ProductPropertyController::class,'index'])->name('products.propertyProduct.index');
Route::post('products/{product}/propertyProduct',[ProductPropertyController::class,'store'])->name('products.propertyProduct.store');
    Route::get('products/{product}/comment/index',[AdminCommentController::class,'index'])->name('products.comment.index');
    Route::delete('products/{comment}/comment/destroy',[AdminCommentController::class,'destroy'])->name('products.comment.destroy');
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $guarded=[];

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }

    public function  hasper($permissionId)
    {
        return $this->permissions()->where('id',$permissionId)->exists();
    }

    public static function findbytitle($title)
    {
        return self::query()->where('title',$title)->firstOrFail();
    }
    //has permission for middleware
    public function haspermission($perTitle)
    {
        return $this->permissions()->where('title',$perTitle)->exists();
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateRoleRequest;
use App\Models\Permission;
use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        return view('admin.roles.index',[
            'roles'=> Role::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
       return view('admin.roles.create',[
           'permissions'=>Permission::all()
       ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CreateRoleRequest $request)
    {
      $newrole=  Role::query()->create([
            'title'=>$request->get('title')
        ]);
        $newrole->permissions()->attach($request->get('permissions'));
        return redirect(route('roles.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(Role $role)
    {
       return view('admin.roles.edit',[
           'permissions'=>Permission::all(),
           'role'=>$role
       ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(CreateRoleRequest $request, Role $role)
    {
        $role->update([
           'title'=>$request->get('title')
        ]);
        $role->permissions()->sync($request->get('permissions'));
        return redirect(route('roles.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Role $role)
    {
       $role->permissions()->detach();
       $role->delete();
       return redirect(route('roles.index'));
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layout.master')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">افزودن نقش</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <form action="{{route('roles.store')}}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="title">عنوان</label>
                            <input type="text" class="form-control" name="title"><br>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                @foreach($permissions as $permission)
                                    <label class="col-sm-2" >
                                    <input style="opacity: 1 !important; position: static !important; left: 0 ; right: 0" type="checkbox" name="permissions[]" value="{{$permission->id}}">
                                        {{$permission->label}}
                                    </label>
                                    <br>
                                @endforeach
                            </div>
                        </div>

                        <input type="submit" name="btn" class="btn btn-primary">
                        <div class="form-group">

                        </div>

                    </form>
              {{--  @extends('admin.layout.errors')--}}
                    @if(count($errors->all())>0)
                        @foreach($errors->all() as $error)

                            {{$error}}

                        @endforeach
                    @endif

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>

        <!-- /.col -->

    </div>

@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layout.master')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">افزودن نقش</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <form action="{{route('roles.update',$role->id)}}" method="post">
                        @csrf
                        @method('PATCH' )
                        <div class="form-group">
                            <label for="title">عنوان</label>
                            <input type="text" value="{{$role->title}}" class="form-control" name="title"><br>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                @foreach($permissions as $permission)
                                    <label class="col-sm-2" >
                                        <input style="opacity: 1 !important; position: static !important; left: 0 ; right: 0" type="checkbox"
                                               @if($role->hasper($permission->id))
                                                   checked
                                                   @endif

                                               name="permissions[]" value="{{$permission->id}}">
                                        {{$permission->label}}
                                    </label>
                                    <br>
                                @endforeach
                            </div>
                        </div>


                        <input type="submit" name="btn" class="btn btn-primary">

                    </form>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>

        <!-- /.col -->
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layout.master')

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">نقش ها</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <table id="example5" class="table table-bordered table-striped" style="width:100%">

                            <thead>
                            <tr>
                                <td>#</td>
                                <td>عنوان</td>
                                <td>ویرایش</td>
                                <td>حذف</td>

                            </tr>
                            </thead>

                            <tbody>
                            @foreach($roles as $role)
                                <tr>
                                    <td>{{$role->id}}</td>
                                    <td>{{$role->title}}</td>
                                    <td><a class="btn btn-primary" href="{{route('roles.edit', $role->id)}}">ویرایش</a></td>
                                    <td>
                                        <form action="{{route('roles.destroy', $role->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <input type="submit" class="btn btn-danger" name="btn"  value="حذف">

                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>#</th>
                                <th>عنوان</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>

        <!-- /.col -->
    </div>
@endsection
@section('scripts')
    <!-- This is data table -->
    <script src="/admin/assets/vendor_components/datatable/datatables.min.js"></script>

    <!-- Superieur Admin for Data Table -->
    <script src="/admin/js/pages/data-table.js"></script>
@endsection