routes/web.php
<?php


use App\Http\Controllers\Admin\ProductPropertyController;
use App\Http\Controllers\Admin\PropertyController;
use App\Http\Controllers\Admin\PropertyGroupController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\CategoriController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\CommentController;
use App\Http\Controllers\Admin\CommentController as AdminCommentController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use App\Http\Controllers\client\HomeController;
use App\Http\Controllers\Admin\PictureController;
use App\Http\Controllers\Admin\DiscountController;
use App\Http\Controllers\Client\RegisterController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/')->name('client.')->group(function (){
    Route::get('/', [HomeController::class , 'index'])->name('index');

    Route::get('products/{product}',[ClientProductController::class , 'show'])->name('products.show');

   Route::get('/register',[RegisterController::class, 'create'])->name('register');
   Route::post('/register/sendmail',[RegisterController::class, 'sendmail'])->name('register.sendmail');
   Route::get('/register/otp/{user}',[RegisterController::class, 'otp'])->name('register.otp');
   Route::post('/register/verifyOtp/{user}',[RegisterController::class, 'verifyOtp'])->name('register.verifyOtp');
   Route::delete('/register/logout',[RegisterController::class, 'logout'])->name('register.logout');

   Route::post('products/comment/{product}/store',[CommentController::class,'store'])->name('product.comment.store');


});





Route::prefix('/adminpanel')/*->middleware([
    \App\Http\Middleware\CheckPermission::class .':readCat',
    'auth'

]) */    ->group(function (){
Route::get('/', function (){
    return view('admin.home');
});

    Route::resource('categories',CategoriController::class);
/*    Route::get('/categories',[App\Http\Controllers\Admin\CategoriController::class,'index'])->name('categories.index');
    Route::get('/categories/create',[App\Http\Controllers\Admin\CategoriController::class,'create'])->name('categories.create');
    Route::post('/categories/store',[App\Http\Controllers\Admin\CategoriController::class,'store'])->name('categories.store');
    Route::get('/categories/{categori}',[App\Http\Controllers\Admin\CategoriController::class,'edit'])->name('categories.edit');
    Route::patch('/categories/{categori}/edit',[App\Http\Controllers\Admin\CategoriController::class,'update'])->name('categories.update');
    Route::delete('/categories/{categori}',[App\Http\Controllers\Admin\CategoriController::class,'destroy'])->name('categories.destroy');*/
Route::resource('brands', \App\Http\Controllers\admin\BrandController::class);

Route::resource('products',ProductController::class);

Route::resource('products.pictures',PictureController::class);

Route::resource('products.discounts',DiscountController::class);

Route::resource('roles',RoleController::class);

Route::resource('users',UserController::class);

Route::resource('propertyGroup',PropertyGroupController::class);

Route::resource('property',PropertyController::class);

Route::get('products/{product}/propertyProduct/create',[ProductPropertyController::class,'create'])->name('products.propertyProduct.create');
Route::get('products/{product}/propertyProduct',[ProductPropertyController::class,'index'])->name('products.propertyProduct.index');
Route::post('products/{product}/propertyProduct',[ProductPropertyController::class,'store'])->name('products.propertyProduct.store');
    Route::get('products/{product}/comment/index',[AdminCommentController::class,'index'])->name('products.comment.index');
    Route::delete('products/{comment}/comment/destroy',[AdminCommentController::class,'destroy'])->name('products.comment.destroy');
});

app/Http/Controllers/Client/CommentController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use App\Models\Product;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

    }
    public function store(Product $product ,Request $request)
    {
Comment::query()->create([
'product_id'=>$product->id,
    'user_id'=>auth()->id(),
    'content'=>$request->get('content')
]);

return redirect()->back();
    }
}

app/Http/Controllers/Client/HomeController.php
<?php

namespace App\Http\Controllers\client;

use App\Http\Controllers\Controller;
use App\Models\Brand;
use App\Models\Categori;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('client.home' , [
          'categories'=>Categori::all()->where('categori_id', null)
/*            'brands'=>Brand::all()*/
            //i pass these parametes with  codes on AppServiceProvider
        ]);
    }
}

app/Http/Controllers/Client/ProductController.php
<?php

namespace App\Http\Controllers\Client;
use App\Http\Controllers\Controller;
use App\Models\Brand;
use App\Models\Categori;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function show(Product $product)
    {

        return view('client.products.show',[
            'product'=>$product,
            'categories'=>Categori::query()->where('categori_id',null)->get(),
            'brands'=>Brand::all()
           //i pass these parametes with  codes on AppServiceProvider

        ]);
   }
}

app/Http/Controllers/Client/RegisterController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Http\Requests\VerifyOtpRequest;
use App\Mail\otpMail;
use App\Models\Categori;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;

class RegisterController extends Controller
{
    public function create()
    {
        return view('client.register.create',[
            'categories'=>Categori::query()->where('categori_id',null)->get()
        ]);
    }

    public function sendmail(Request $request)
    {
        $this->validate($request,[
           'email'=>['required','email']
        ]);

       $otp= random_int (10000,99999);

       $userquery= User::query()->where('email',$request->get('email'));

       if ($userquery->exists()){
           $user=$userquery->first();
           $user->update([
              'password'=>bcrypt($otp)
           ]);
       }
       else{
           $user= User::query()->create([
               'role_id'=>Role::findbytitle('normaluser')->id ,
               'email'=>$request->get('email'),
               'password'=>bcrypt($otp)
           ]);
       }


        //send otp by email to user
     Mail::to($user->email)->send(new otpMail($otp));
        return redirect(route('client.register.otp',$user));
        //register.otp route is where user should enter otp
    }

    public function otp(User $user)
    {
        return view('client.register.otp',[
            'categories'=>Categori::query()->where('categori_id',null)->get(),
           'user'=>$user
        ]);
    }

    public function verifyOtp(User $user , VerifyOtpRequest $request)
    {
        if(!Hash::check($request->get('otp'),$user->password)){

            return back()->withErrors(['otp'=>'رمزتون اشتباهه']);
        }
        auth()->login($user);
        return redirect(route('client.index'));
    }

    public function logout()
    {
        auth()->logout();
        return redirect(route('client.index'));
    }
}

resources/views/client/register/create.blade.php
@extends('client.layout.master')
@section('content')

    <<div id="container">
        <div class="container">
            <!-- Breadcrumb Start-->
            <ul class="breadcrumb">
                <li><a href="index.html"><i class="fa fa-home"></i></a></li>
                <li><a href="login.html">حساب کاربری</a></li>
                <li><a href="register.html">ثبت نام</a></li>
            </ul>
            <!-- Breadcrumb End-->
            <div class="row">
                <!--Middle Part Start-->
                <div class="col-sm-9" id="content">
                    <h1 class="title">ثبت نام حساب کاربری</h1>
                    <p>اگر قبلا حساب کاربریتان را ایجاد کرد اید جهت ورود به <a href="login.html">صفحه لاگین</a> مراجعه کنید.</p>
                    <form class="form-horizontal" method="post" action="{{route('client.register.sendmail')}}">
                        @csrf
                        <fieldset id="account">
                            <legend>برای دریافت رمز یکبار مصرف ایمیل خود را وارد کنید</legend>
                            <div style="display: none;" class="form-group required">
                                <label class="col-sm-2 control-label">گروه مشتری</label>
                                <div class="col-sm-10">
                                    <div class="radio">
                                        <label>
                                            <input type="radio" checked="checked" value="1" name="customer_group_id">
                                            پیشفرض</label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group required">
                                <label for="input-email" class="col-sm-2 control-label">آدرس ایمیل</label>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control" id="input-email" placeholder="آدرس ایمیل" value="" name="email">
                                </div>
                            </div>
                        </fieldset>

                        <div class="buttons">
                            <div class="pull-right">
                                <input type="submit" class="btn btn-primary" value="ادامه">
                            </div>
                        </div>
                    </form>
                </div>
                <!--Middle Part End -->
                <!--Right Part Start -->


                <!--Right Part End -->
            </div>
        </div>
    </div>


    @endsection

resources/views/client/register/otp.blade.php
@extends('client.layout.master')
@section('content')

    <<div id="container">
        <div class="container">
            <!-- Breadcrumb Start-->
            <ul class="breadcrumb">
                <li><a href="index.html"><i class="fa fa-home"></i></a></li>
                <li><a href="login.html">حساب کاربری</a></li>
                <li><a href="register.html">ثبت نام</a></li>
            </ul>
            <!-- Breadcrumb End-->
            <div class="row">
                <!--Middle Part Start-->
                <div class="col-sm-9" id="content">
                    <h1 class="title">ثبت نام حساب کاربری</h1>
                  {{--  <p>اگر قبلا حساب کاربریتان را ایجاد کرد اید جهت ورود به <a href="login.html">صفحه لاگین</a> مراجعه کنید.</p>--}}
                    <form class="form-horizontal" method="post" action="{{route('client.register.verifyOtp',$user)}}">
                        @csrf
                        <fieldset id="account">
                            <legend>رمز یکبار مصرف ارسال شده به ایمیلتان را وارد کنید:</legend>
                            <div style="display: none;" class="form-group required">
                                <label class="col-sm-2 control-label">گروه مشتری</label>
                                <div class="col-sm-10">
                                    <div class="radio">
                                        <label>
                                            <input type="radio" checked="checked" value="1" name="customer_group_id">
                                            پیشفرض</label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group required">
                                <label for="input-email" class="col-sm-2 control-label">رمز یکبار مصرف</label>
                                <div class="col-sm-10">
                                    <input type="text" min="5" max="5" class="form-control" id="input-email" placeholder="رمز یکبار مصرف" value="" name="otp">
                                </div>
                            </div>
                        </fieldset>

                        <div class="buttons">
                            <div class="pull-right">
                                <input type="submit" class="btn btn-primary" value="ادامه">
                            </div>
                        </div>
                    </form>
                    @if(count($errors->all())>0)
                        @foreach($errors->all() as $error)

                            {{$error}}

                        @endforeach
                    @endif
                </div>
                <!--Middle Part End -->
                <!--Right Part Start -->

                <!--Right Part End -->
            </div>
        </div>
    </div>


@endsection