routes/web.php
<?php


use App\Http\Controllers\Admin\ProductPropertyController;
use App\Http\Controllers\Admin\PropertyController;
use App\Http\Controllers\Admin\PropertyGroupController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\CategoriController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\CommentController;
use App\Http\Controllers\Admin\CommentController as AdminCommentController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use App\Http\Controllers\client\HomeController;
use App\Http\Controllers\Admin\PictureController;
use App\Http\Controllers\Admin\DiscountController;
use App\Http\Controllers\Client\RegisterController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/')->name('client.')->group(function (){
    Route::get('/', [HomeController::class , 'index'])->name('index');

    Route::get('products/{product}',[ClientProductController::class , 'show'])->name('products.show');

   Route::get('/register',[RegisterController::class, 'create'])->name('register');
   Route::post('/register/sendmail',[RegisterController::class, 'sendmail'])->name('register.sendmail');
   Route::get('/register/otp/{user}',[RegisterController::class, 'otp'])->name('register.otp');
   Route::post('/register/verifyOtp/{user}',[RegisterController::class, 'verifyOtp'])->name('register.verifyOtp');
   Route::delete('/register/logout',[RegisterController::class, 'logout'])->name('register.logout');

   Route::post('products/comment/{product}/store',[CommentController::class,'store'])->name('product.comment.store');


});





Route::prefix('/adminpanel')/*->middleware([
    \App\Http\Middleware\CheckPermission::class .':readCat',
    'auth'

]) */    ->group(function (){
Route::get('/', function (){
    return view('admin.home');
});

    Route::resource('categories',CategoriController::class);
/*    Route::get('/categories',[App\Http\Controllers\Admin\CategoriController::class,'index'])->name('categories.index');
    Route::get('/categories/create',[App\Http\Controllers\Admin\CategoriController::class,'create'])->name('categories.create');
    Route::post('/categories/store',[App\Http\Controllers\Admin\CategoriController::class,'store'])->name('categories.store');
    Route::get('/categories/{categori}',[App\Http\Controllers\Admin\CategoriController::class,'edit'])->name('categories.edit');
    Route::patch('/categories/{categori}/edit',[App\Http\Controllers\Admin\CategoriController::class,'update'])->name('categories.update');
    Route::delete('/categories/{categori}',[App\Http\Controllers\Admin\CategoriController::class,'destroy'])->name('categories.destroy');*/
Route::resource('brands', \App\Http\Controllers\admin\BrandController::class);

Route::resource('products',ProductController::class);

Route::resource('products.pictures',PictureController::class);

Route::resource('products.discounts',DiscountController::class);

Route::resource('roles',RoleController::class);

Route::resource('users',UserController::class);

Route::resource('propertyGroup',PropertyGroupController::class);

Route::resource('property',PropertyController::class);

Route::get('products/{product}/propertyProduct/create',[ProductPropertyController::class,'create'])->name('products.propertyProduct.create');
Route::get('products/{product}/propertyProduct',[ProductPropertyController::class,'index'])->name('products.propertyProduct.index');
Route::post('products/{product}/propertyProduct',[ProductPropertyController::class,'store'])->name('products.propertyProduct.store');
    Route::get('products/{product}/comment/index',[AdminCommentController::class,'index'])->name('products.comment.index');
    Route::delete('products/{comment}/comment/destroy',[AdminCommentController::class,'destroy'])->name('products.comment.destroy');
});

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;
    protected $guarded=[

    ];
}

app/Http/Controllers/Admin/BrandController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateBrandRequest;
use App\Models\Brand;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        return view('admin.brands.index' , [
                'brands'=>Brand::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('admin.brands.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateBrandRequest $request)
    {

        $path=$request->file('image')->storeAs('public/images',$request->file('image')->getClientOriginalName());
        Brand::query()->create([
            'name'=>$request->get('name'),
            'image'=>$path
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(Brand $brand)
    {
        return view('admin.brands.edit',[
            'brand'=>$brand
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, Brand $brand)
    {
        if ($request->hasFile('image')){
            $path=$request->file('image')->storeAs('public/image',$request->file('image')->getClientOriginalName());
        }
        else{
            $path= $brand->image;
        }

        $brand->update([
           'name'=>$request->get('name'),
           'image'=>$path
        ]);
        return redirect(route('brands.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Brand $brand)
    {
       $brand->delete();
       return  redirect(route('brands.index'));
    }
}

resources/views/admin/brands/create.blade.php
@extends('admin.layout.master')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">افزودن برند</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <form action="{{route('brands.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="name">اسم</label>
                        <input type="text" class="form-control" name="name" ><br>
                        </div>

                        <div class="form-group">
                            <label for="image"> عکس</label>
                            <input type="file"  name="image" class="form-control"><br>

                        </div>
                        <input type="submit" name="btn" class="btn btn-primary">

                    </form>

                </div>
                <!-- /.box-body -->
            </div>

            @if(count($errors->all()) > 0 )
                @foreach($errors->all() as $error)
                    {{$error}}
                @endforeach
            @endif
            <!-- /.box -->
        </div>

        <!-- /.col -->
    </div>
@endsection

resources/views/admin/brands/edit.blade.php
@extends('admin.layout.master')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">افزودن برند</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <form action="{{route('brands.update',$brand)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('patch')
                        <div class="form-group">
                            <label for="name">اسم</label>
                            <input type="text" class="form-control" name="name" value="{{$brand->name}}" ><br>
                        </div>

                        <div class="form-group">
                            <label for="image"> عکس</label>
                            <input type="file"  name="image" class="form-control"><br>
                        </div>
                        <div class="form-group">
                            <label for="image"> عکس</label>
                           <img width="50" src="{{str_replace('public','/storage', $brand->image)}}">
                        </div>
                        <input type="submit" name="btn" class="btn btn-primary">

                    </form>

                </div>
                <!-- /.box-body -->
            </div>

        @if(count($errors->all()) > 0 )
            @foreach($errors->all() as $error)
                {{$error}}
            @endforeach
        @endif
        <!-- /.box -->
        </div>

        <!-- /.col -->
    </div>
@endsection

resources/views/admin/brands/index.blade.php
@extends('admin.layout.master')

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">برند ها</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <table id="example5" class="table table-bordered table-striped" style="width:100%">

                            <thead>
                            <tr>
                                <td>#</td>
                                <td>اسم</td>
                                <td>تصویر</td>
                                <td>ویرایش</td>
                                <td>حذف</td>

                            </tr>
                            </thead>

                            <tbody>
                            @foreach($brands as $brand)
                                <tr>
                                    <td>{{$brand->id}}</td>
                                    <td>{{$brand->name}}</td>
                                    <td><img width="50" src="{{str_replace('public','/storage',$brand->image)}}" alt="image"></td>
                                    <td><a class="btn btn-primary" href="{{route('brands.edit', $brand->id)}}">ویرایش</a></td>
                                    <td>
                                        <form action="{{route('brands.destroy', $brand)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <input type="submit" class="btn btn-danger" name="btn"  value="حذف">

                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>#</th>
                                <th>اسم</th>
                                <th>دسته والد</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>

        <!-- /.col -->
    </div>
@endsection
@section('scripts')
    <!-- This is data table -->
    <script src="/admin/assets/vendor_components/datatable/datatables.min.js"></script>

    <!-- Superieur Admin for Data Table -->
    <script src="/admin/js/pages/data-table.js"></script>
@endsection